package rules

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"doublebook/infra/utils"
	"gopkg.in/yaml.v3"
)

// ---------------------------------------------------------------------------
// Loading and Saving
// ---------------------------------------------------------------------------

// LoadRuleSet reads a ruleset from a YAML file.
func LoadRuleSet(path string) (*RuleSet, error) {
	path = utils.ExpandHome(path)
	
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("reading ruleset %q: %w", path, err)
	}
	
	var rs RuleSet
	if err := yaml.Unmarshal(data, &rs); err != nil {
		return nil, fmt.Errorf("parsing ruleset %q: %w", path, err)
	}
	
	applyRuleSetDefaults(&rs)
	
	if err := rs.Validate(); err != nil {
		return nil, fmt.Errorf("invalid ruleset %q: %w", path, err)
	}
	
	if err := rs.Compile(); err != nil {
		return nil, fmt.Errorf("compiling ruleset %q: %w", path, err)
	}
	
	return &rs, nil
}

// SaveRuleSet writes a ruleset to a YAML file.
func SaveRuleSet(rs *RuleSet, path string) error {
	path = utils.ExpandHome(path)
	
	// Ensure directory exists
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("creating directory %q: %w", dir, err)
	}
	
	data, err := yaml.Marshal(rs)
	if err != nil {
		return fmt.Errorf("encoding ruleset: %w", err)
	}
	
	// Add header comment
	header := `# DoubleBook Import Rules
# Generated by the Rules Engine
# 
# This file defines how to import data from a specific source.
# Edit the mappings below to customize how columns are processed.
#
# Available transform functions:
#   String: uppercase, lowercase, titlecase, trim, replace, regex_extract, prefix, suffix, truncate, clean
#   Combine: concat, join, format
#   Date: parse_date, format_date
#   Number: parse_number, abs, negate
#   Conditional: default, coalesce, if_empty, if_contains
#   Lookup: map, extract_account
#

`
	content := header + string(data)
	
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		return fmt.Errorf("writing ruleset to %q: %w", path, err)
	}
	
	return nil
}

// applyRuleSetDefaults fills in default values for missing fields.
func applyRuleSetDefaults(rs *RuleSet) {
	if rs.Version == "" {
		rs.Version = "1"
	}
	
	// Format defaults
	if rs.Format.Type == "" {
		rs.Format.Type = "csv"
	}
	if rs.Format.Delimiter == "" {
		rs.Format.Delimiter = ","
	}
	if rs.Format.Encoding == "" {
		rs.Format.Encoding = "utf-8"
	}
	if rs.Format.SkipLines == 0 {
		rs.Format.SkipLines = 1
	}
	
	// Account defaults
	if rs.DefaultDebitAccount == "" {
		rs.DefaultDebitAccount = "expenses:unknown"
	}
	if rs.DefaultCreditAccount == "" {
		rs.DefaultCreditAccount = "income:unknown"
	}
	if rs.Currency == "" {
		rs.Currency = "USD"
	}
}

// ---------------------------------------------------------------------------
// Discovery
// ---------------------------------------------------------------------------

// ListRuleSets finds all ruleset files in the given directory.
func ListRuleSets(dir string) ([]string, error) {
	dir = utils.ExpandHome(dir)
	
	entries, err := os.ReadDir(dir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("reading directory %q: %w", dir, err)
	}
	
	var files []string
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		name := entry.Name()
		if strings.HasSuffix(name, ".yaml") || strings.HasSuffix(name, ".yml") {
			files = append(files, filepath.Join(dir, name))
		}
	}
	
	return files, nil
}

// FindRuleSet searches for a ruleset by name in common locations.
func FindRuleSet(name string) (string, error) {
	// Try exact path first
	if _, err := os.Stat(name); err == nil {
		return name, nil
	}
	
	// Try with extensions
	for _, ext := range []string{".yaml", ".yml", ".rules.yaml", ".rules.yml"} {
		path := name + ext
		if _, err := os.Stat(path); err == nil {
			return path, nil
		}
	}
	
	// Try in ~/.doublebook/rules/
	home, _ := os.UserHomeDir()
	rulesDir := filepath.Join(home, ".doublebook", "rules")
	
	for _, ext := range []string{".yaml", ".yml", ".rules.yaml", ".rules.yml"} {
		path := filepath.Join(rulesDir, name+ext)
		if _, err := os.Stat(path); err == nil {
			return path, nil
		}
	}
	
	return "", fmt.Errorf("ruleset %q not found", name)
}

// DefaultRulesDir returns the default directory for ruleset files.
func DefaultRulesDir() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".doublebook", "rules")
}
